version: "3.8"

services:
  app:
    build: 
      dockerfile: "Dockerfile"
      context: "."
    volumes:
      - ./:/app:rw,cached
      - /app/node_modules
    ports:
      - "4000:4000"
      - "5555:5555"
    environment:
      SERVER_DATABASE_NAME: taskberry
      PRISMA_DATABASE_URL: mysql://root:root@mysql:3306/taskberry
    depends_on:
      - mysql

  mysql:
    image: mysql
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
